# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release latest starter and migration packages

on:
  push:
    branches: [ master, main ]
    tags: [ '*' ]

jobs:
  zip-and-release-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Prepare release folder
        run: |
          mkdir packages

      - name: Zip starter
        uses: montudor/action-zip@v1
        with:
          args: >
            zip -r packages/starter.zip . \
                \
                -x "*.git/*" \
                \
                -x ".github/scripts/update-version.sh" \
                -x ".github/workflows/buildscript-maintenance.yml" \
                -x ".github/workflows/release-packages.yml" \
                \
                -x "*docs/*" \
                -x "README.md" \
                -x "LICENSE" \
                -x "gtnhShared/*" \
                \
                -x "packages/" \
                -x "packages/starter.zip" \
                -x "packages/migration.zip"

      - name: Zip migration
        uses: montudor/action-zip@v1
        with:
          args: >
            zip -r packages/migration.zip . \
                \
                -x "*.git/*" \
                \
                -x ".github/scripts/update-version.sh" \
                -x ".github/workflows/buildscript-maintenance.yml" \
                -x ".github/workflows/release-packages.yml" \
                \
                -x "*docs/*" \
                -x "*src/*" \
                -x "LICENSE" \
                -x "README.md" \
                -x "gtnhShared/*" \
                \
                -x "packages/" \
                -x "packages/starter.zip" \
                -x "packages/migration.zip"

      - name: Update latest tag
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ (github.ref == 'master' || github.ref == 'main') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-packages"
          prerelease: true
          title: "Latest starter and migration packages"
          files: packages/*

      - name: Release named version
        if: ${{ !(github.ref == 'master' || github.ref == 'main') }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}-packages"
          prerelease: false
          title: "${{ env.RELEASE_VERSION }} starter and migration packages"
          files: packages/*
